[package]
name = "collatz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true

[dependencies]
num_cpus = "1.13.0"
crossbeam = { version = "0.8" }